### PR TITLE
Checksum the download of the binaries 

### PR DESCRIPTION
**Pull request by blueshift-brasil**
Checksum the download of the binaries of the Accumulo, Zookeeper and Hadoop.

### CODE REVIEW

**Comment by keith-turner** [comment]
The readme currently has a command for building with custom versions.  It should be updated with the hash build args.  Since its so long could update it with a multi-line command like the following.

```bash
docker build --build-arg HADOOP_HASH=0f90ef671530c2aa42cde6da111e8e47e9cd659e \
             --build-arg HADOOP_VERSION=2.7.5 \
             --build-arg ACCUMULO_HASH=30b9a8af5379f680077aaf88b1fea22595be6934 \
             --build-arg ACCUMULO_VERSION=1.7.3 \
             --build-arg ZOOKEEPER_HASH=9268b4aed71dccad3d7da5bfa5573b66d2c9b565 \
             --build-arg ZOOKEEPER_VERSION=3.4.11 \
              -t fluo .
```

**Comment by blueshift-brasil** [comment]
Hello Keith!
Can I update the README and Dockerfile to reflect this versions?
The README file has a version in the **Obtain the Docker image** session and other verion in the **Build the Docker image** session. Can I fix it too?

Actually, are there newer version?

**Comment by blueshift-brasil** [comment]
What about those versions:
Software = Version 
[Fluo] = 1.2.0   
[Accumulo] = 1.8.1   
[Hadoop]  = 2.7.5   
[Zookeeper] = 3.4.9

**Comment by keith-turner** [comment]
@alanblueshift  the versions sound good.  I would bring ZK to the latest 3.4 version of 3.4.11.

[Accumulo] = 1.8.1
[Hadoop] = 2.7.5
[Zookeeper] = 3.4.11

**Comment by blueshift-brasil** [comment]
Sorry for the multiple pull requests. I have added a debug flag in a line and I decided take it off.

**Comment by mikewalch** [comment]
@alanblueshift, no worries about pushing multiple commits to the pull request. They can be squashed into one before it is merged.

**Comment by keith-turner** [comment]
The changes looked good @alanblueshift.  I squashed and merged.  Thanks again.

**Pull request merged**
