### PR TITLE
Fix to download from Apache mirrors instead of archive #9

### PR DESCRIPTION
**Pull request by blueshift-brasil**

### CODE REVIEW

**Review by mikewalch — APPROVED** [review]
Looks good to me. I was able to build and run image locally.

**Review by ctubbsii — APPROVED** [review]
+1 from me for the changes, but it does raise a question for me: is there a checksum verification step after the download? That would be a good thing to do, especially if there's a possibility of getting it from a non-https and/or non-ASF site.

**Comment by keith-turner** [comment]
@ctubbsii I opened #11

**Comment by keith-turner** [comment]
@alanblueshift thanks for the contribution.  Would you like to be added to the [Fluo people page](http://fluo.apache.org/people/) as a contributor?  If so you can let me know what info you would like added or you can make a PR to the [website repo](https://github.com/apache/fluo-website).  

The Apache Fluo project tweets about first contributions.  Are you ok with a tweet about this contribution?  And if so would you like the twitter handle alancamillo mentioned or some other handle?

**Comment by blueshift-brasil** [comment]
Sure! It’ll be a pleasure.

My *Twitter* user is: alancamillo

*Name:* Alan Camillo

*E-mail:* alan@blueshift.com.br



Thank you for your invite!

Alan Camillo



*From:* Keith Turner [mailto:notifications@github.com]
*Sent:* Wednesday, December 20, 2017 10:59 AM
*To:* apache/fluo-docker <fluo-docker@noreply.github.com>
*Cc:* alanblueshift <alan@blueshift.com.br>; Mention <
mention@noreply.github.com>
*Subject:* Re: [apache/fluo-docker] Fix to download from Apache mirrors
instead of archive #9 (#10)



@alanblueshift <https://github.com/alanblueshift> thanks for the
contribution. Would you like to be added to the Fluo people page
<http://fluo.apache.org/people/> as a contributor? If so you can let me
know what info you would like added or you can make a PR to the website repo
<https://github.com/apache/fluo-website>.

The Apache Fluo project tweets about first contributions. Are you ok with a
tweet about this contribution? And if so would you like the twitter handle
alancamillo mentioned or some other handle?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache/fluo-docker/pull/10#issuecomment-353056591>, or mute
the thread

**Pull request merged**
